/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 vr_apartment_loft_interior_baked.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Room1(props) {
  const { nodes, materials } = useGLTF('/models/vr_apartment_loft_interior_baked.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes['Stairs_���������10003_0'].geometry} material={materials['10.003']} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 110.277]} />
        <mesh geometry={nodes['House_���������10_0'].geometry} material={materials.material} position={[115.136, 409.631, -276.927]} rotation={[-Math.PI / 2, 0, 0]} scale={[409.821, 566.195, 409.821]} />
        <mesh geometry={nodes['2nd_floor_���������10001_0'].geometry} material={materials['10.001']} position={[230.759, 405.977, -470.328]} rotation={[-Math.PI / 2, 0, 0]} scale={[290.07, 367.828, 9.152]} />
        <mesh geometry={nodes['floor_���������10002_0'].geometry} material={materials['10.002']} position={[115.136, -3.496, -107.309]} rotation={[-Math.PI / 2, 0, 0]} scale={[409.821, 566.195, 409.821]} />
        <mesh geometry={nodes.Window_Material001_0.geometry} material={materials['Material.001']} position={[115.136, 409.631, -169.044]} rotation={[-Math.PI / 2, 0, 0]} scale={[409.821, 566.195, 409.821]} />
        <mesh geometry={nodes.Sphere_Material002_0.geometry} material={materials['Material.002']} position={[0, 306.181, 74.714]} rotation={[Math.PI / 2, 0, 0]} scale={[-7.827, 7.827, 7.827]} />
        <mesh geometry={nodes.lighting_Material004_0.geometry} material={materials['Material.004']} position={[0, 229.866, 10.875]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[33.778, 20.831, 33.778]} />
        <mesh geometry={nodes.Sphere001_Material002_0.geometry} material={materials['Material.002']} position={[0, 217.816, 10.875]} rotation={[Math.PI / 2, 0, 0]} scale={[-7.827, 7.827, 7.827]} />
        <mesh geometry={nodes['2nd_floor_lighting_Material006_0'].geometry} material={materials['Material.006']} position={[230.759, 405.977, -470.328]} rotation={[-Math.PI / 2, 0, 0]} scale={[290.07, 367.828, 9.152]} />
        <mesh geometry={nodes.outside_Material009_0.geometry} material={materials['Material.009']} position={[-654.395, 99.503, -442.7]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[478.365, 292.061, 478.365]} />
        <mesh geometry={nodes.painting_Material010_0.geometry} material={materials['Material.010']} position={[-95.418, 138.411, -478.869]} rotation={[-1.719, 0, 0]} scale={[70.789, 3.492, 138.028]} />
        <mesh geometry={nodes.bottle2_Material008_0.geometry} material={materials['Material.008']} position={[32.399, 74.807, 164.086]} rotation={[-Math.PI / 2, 0, 0]} scale={4.664} />
        <mesh geometry={nodes.table_Material011_0.geometry} material={materials['Material.011']} position={[22.445, 36.219, 177.316]} rotation={[0, -1.504, 1.571]} scale={[28.774, 20.806, 33.738]} />
        <mesh geometry={nodes.sofa_Soft_Black_Fabric_0.geometry} material={materials.Soft_Black_Fabric} position={[-84.424, 76.72, 90.033]} rotation={[-Math.PI, Math.PI / 3, Math.PI / 2]} scale={[39.955, 73.885, 24.623]} />
        <mesh geometry={nodes.piping_Soft_Black_Fabric001_0.geometry} material={materials['Soft_Black_Fabric.001']} position={[-75.158, 62.067, -2.552]} rotation={[-Math.PI, -Math.PI / 6, -Math.PI / 2]} scale={[28.379, 52.06, 18.743]} />
        <mesh geometry={nodes.carpet_Fabric_Upholstery_001a_0.geometry} material={materials.Fabric_Upholstery_001a} position={[-16.963, 3.795, 55.583]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-223.055, 223.055, 3.386]} />
        <mesh geometry={nodes.bottle1_Material007_0.geometry} material={materials['Material.007']} position={[28.423, 81.05, 181.481]} rotation={[-Math.PI / 2, 0, 0]} scale={10.659} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/vr_apartment_loft_interior_baked.glb')
